---
init_users:
  - user_name:     pandemonium
    user_comment:  'Mike Maf'
    user_groups:   [ 'users', 'pandemonium', 'wheel' ]
    user_home:     /home/pandemonium
    user_password: $6$mysecretsaltforv$eozBiDFSv4on7Vd7UhFfD4at53WD4ngNiFsPmJyoMGSBpXp9fmOnArp2l5Z8I/YYJ.onT6DDEKRcWMO9RUIwb0
