---
- name: Midgar installation
  hosts: all
  become: true
  # become_method:        sudo
  # become_user:          root
  collections:
    - pandemonium1986.k8s_toolbox
  tasks:
    - import_role:
        name: pandemonium1986.init
    - import_role:
        name: pandemonium1986.ohmyzsh
    - import_role:
        name: pandemonium1986.pip
    - import_role:
        name: geerlingguy.docker
    - import_role:
        name: minikube
    - import_role:
        name: kubectx
    - import_role:
        name: k9s
    - import_role:
        name: stern
    - import_role:
        name: helm
    - name: Ensure softwares are configured
      block:
        - name: Ensure pandemonium dotfiles are installed
          git:
            repo: "https://github.com/Pandemonium1986/dotfiles"
            dest: /home/pandemonium/git/Pandemonium1986/dotfiles
            update: false
        - name: Ensure tmuxifier is install
          git:
            repo: "https://github.com/jimeh/tmuxifier.git"
            dest: /home/pandemonium/.tmuxifier
            update: true
      become: true
      become_user: pandemonium
