---
- src:     pandemonium1986.ansible
  version: 2.3.1
- src:     pandemonium1986.helm
  version: 1.0.1
- src:     pandemonium1986.init
  version: 2.4.1
- src:     pandemonium1986.k9s
  version: 1.0.0
- src:     pandemonium1986.kubectl
  version: 1.0.1
- src:     pandemonium1986.kubectx
  version: 1.0.1
- src:     pandemonium1986.minikube
  version: 1.0.1
- src:     pandemonium1986.ohmyzsh
  version: 2.3.0
- src:     pandemonium1986.pip
  version: 2.1.0
- src:     pandemonium1986.stern
  version: 1.1.0
