---
name:                Vagrant
on:
  # schedule:
  #   - cron:        "0 21 * * *"
  push:
    branches:
      - develop
  pull_request:
    types:
      - main
      - master
  workflow_dispatch:

jobs:
  # lint:
  #   name:                      "Ansible: Lint"
  #   runs-on:       ubuntu-latest
  #   steps:
  #     - name:                  "Init: Run checkout@v2"
  #       uses:      actions/checkout@v2
  #     - name:                  "Ansible: Lint role"
  #       uses:      ansible/ansible-lint-action@master
  #       with:
  #         targets: "./"
  vagrant:
    name:            Vagrant Build and Push
    runs-on:         macos-10.15
    strategy:
      fail-fast:     false
      matrix:
        boxes:
          # - "cts7"
          # - "cts"
          - "deb"
          # - "ubt"
          # - "mnt"
    # needs:
    #   - lint
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name:        debug1
        run:         echo $PATH
      # - name:        "Init: Run checkout@v2"
      #   uses:      actions/checkout@v2
      - name:      "Init: Install Ansible "
        run:       |
          sudo pip install ansible
          sudo pip show ansible
      - name:        debug2
        run:         ansible --version
      # - name:        "Vagrant: Test"
      #   run:       vagrant up midgar-${{ matrix.boxes }} --provision-with shell-config,ansible-midgar,shell-vagrant,shell-cleanup
