---
name:                      Vagrant
on:
  # schedule:
  #   - cron:              "0 21 * * *"
  push:
    branches:
      - develop
  pull_request:
    types:
      - main
      - master
  workflow_dispatch:

jobs:
  # lint:
  #   name:                      "Ansible: Lint"
  #   runs-on:             ubuntu-latest
  #   steps:
  #     - name:                  "Init: Run checkout@v2"
  #       uses:            actions/checkout@v2
  #     - name:                  "Ansible: Lint role"
  #       uses:            ansible/ansible-lint-action@master
  #       with:
  #         targets:       "./"
  vagrant:
    name:                  Vagrant Build and Push
    runs-on:               macos-10.15
    env:
      ANSIBLE_FORCE_COLOR: "1"
      PY_COLORS:           "1"
      ANSIBLE_PIPELINING:  "true"
    strategy:
      fail-fast:           false
      matrix:
        boxes:
          # - "cts7"
          # - "cts"
          - "deb"
          # - "ubt"
          # - "mnt"
    # needs:
    #   - lint
    steps:
      - name:              Init run checkout
        uses:              actions/checkout@v2
      - name:              Set up Python
        uses:              actions/setup-python@v2
        with:
          python-version:  '3.8'
          architecture:    x64
      - name:              Init install Ansible
        run:               sudo pip install ansible~=3.0
      - name:              Vagrant Build
        run:               vagrant up midgar-${{ matrix.boxes }} --provision-with shell-config,ansible-midgar,shell-vagrant,shell-cleanup
